# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

def shared_pods
  # Pods for Reciplease
  pod 'Alamofire'
  pod 'SDWebImage'
end


target 'Reciplease' do
  shared_pods
end

target 'RecipleaseTests' do
  shared_pods
end
